import { Emotion, Trigger, BodySensation, Urge, CopingExercise } from '@/types';

export const EMOTIONS: Emotion[] = [
  { id: 'e1', label: 'Angry', emoji: '😤' },
  { id: 'e2', label: 'Afraid', emoji: '😰' },
  { id: 'e3', label: 'Sad', emoji: '😢' },
  { id: 'e4', label: 'Abandoned', emoji: '💔' },
  { id: 'e5', label: 'Ashamed', emoji: '😞' },
  { id: 'e6', label: 'Jealous', emoji: '😒' },
  { id: 'e7', label: 'Empty', emoji: '🫥' },
  { id: 'e8', label: 'Overwhelmed', emoji: '😵' },
  { id: 'e9', label: 'Anxious', emoji: '😟' },
  { id: 'e10', label: 'Numb', emoji: '😶' },
  { id: 'e11', label: 'Desperate', emoji: '😫' },
  { id: 'e12', label: 'Misunderstood', emoji: '🥺' },
];

export const TRIGGERS: Trigger[] = [
  { id: 't1', label: 'Someone ignored me', category: 'relationship' },
  { id: 't2', label: 'Feeling rejected', category: 'relationship' },
  { id: 't3', label: 'Fear of abandonment', category: 'relationship' },
  { id: 't4', label: 'Conflict with someone', category: 'relationship' },
  { id: 't5', label: 'Perceived criticism', category: 'relationship' },
  { id: 't6', label: 'Feeling not good enough', category: 'self' },
  { id: 't7', label: 'Identity confusion', category: 'self' },
  { id: 't8', label: 'Comparing myself', category: 'self' },
  { id: 't9', label: 'Change in plans', category: 'situation' },
  { id: 't10', label: 'Being alone', category: 'situation' },
  { id: 't11', label: 'A painful memory', category: 'memory' },
  { id: 't12', label: 'Something else', category: 'other' },
];

export const BODY_SENSATIONS: BodySensation[] = [
  { id: 'b1', label: 'Chest tightness', area: 'chest' },
  { id: 'b2', label: 'Racing heart', area: 'chest' },
  { id: 'b3', label: 'Stomach knots', area: 'stomach' },
  { id: 'b4', label: 'Nausea', area: 'stomach' },
  { id: 'b5', label: 'Tension in jaw', area: 'head' },
  { id: 'b6', label: 'Headache', area: 'head' },
  { id: 'b7', label: 'Shaking', area: 'body' },
  { id: 'b8', label: 'Feeling hot', area: 'body' },
  { id: 'b9', label: 'Lump in throat', area: 'throat' },
  { id: 'b10', label: 'Can\'t breathe', area: 'chest' },
  { id: 'b11', label: 'Numbness', area: 'body' },
  { id: 'b12', label: 'Heavy limbs', area: 'body' },
];

export const URGES: Urge[] = [
  { id: 'u1', label: 'Send an angry text', risk: 'medium' },
  { id: 'u2', label: 'Push someone away', risk: 'medium' },
  { id: 'u3', label: 'Beg for reassurance', risk: 'low' },
  { id: 'u4', label: 'Isolate completely', risk: 'medium' },
  { id: 'u5', label: 'Quit / end things', risk: 'high' },
  { id: 'u6', label: 'Lash out at someone', risk: 'high' },
  { id: 'u7', label: 'Self-harm', risk: 'high' },
  { id: 'u8', label: 'Substance use', risk: 'high' },
  { id: 'u9', label: 'Cry uncontrollably', risk: 'low' },
  { id: 'u10', label: 'Scroll obsessively', risk: 'low' },
];

export const COPING_EXERCISES: CopingExercise[] = [
  {
    id: 'c1',
    title: '5-4-3-2-1 Grounding',
    description: 'Use your senses to anchor yourself in the present moment.',
    category: 'grounding',
    duration: '3 min',
    steps: [
      'Name 5 things you can SEE right now',
      'Name 4 things you can TOUCH right now',
      'Name 3 things you can HEAR right now',
      'Name 2 things you can SMELL right now',
      'Name 1 thing you can TASTE right now',
      'Take a deep breath. You are here. You are safe.',
    ],
  },
  {
    id: 'c2',
    title: 'Ice Dive',
    description: 'Activate your dive reflex to quickly reduce emotional intensity.',
    category: 'grounding',
    duration: '1 min',
    steps: [
      'Fill a bowl with cold water and ice',
      'Hold your breath',
      'Submerge your face for 30 seconds',
      'If no bowl: hold ice cubes in your hands',
      'Focus on the physical sensation',
      'Notice how your heart rate slows down',
    ],
  },
  {
    id: 'c3',
    title: 'Self-Soothe Kit',
    description: 'Comfort yourself through your senses, like caring for a friend.',
    category: 'self-soothing',
    duration: '5 min',
    steps: [
      'Wrap yourself in something soft and warm',
      'Put on calming music or nature sounds',
      'Make a warm drink — tea, cocoa, anything comforting',
      'Light a candle or use a scent you love',
      'Place one hand on your heart, one on your belly',
      'Say: "This is hard, and I\'m allowed to take care of myself."',
    ],
  },
  {
    id: 'c4',
    title: 'Compassionate Letter',
    description: 'Write to yourself the way a loving friend would.',
    category: 'self-soothing',
    duration: '5 min',
    steps: [
      'Imagine someone who deeply loves you',
      'What would they say to you right now?',
      'Write it down, starting with "Dear one..."',
      'Include: what they see in you, why this is hard, what they wish for you',
      'Read it back to yourself slowly',
      'Let the words land. You deserve this kindness.',
    ],
  },
  {
    id: 'c5',
    title: 'Check the Facts',
    description: 'Separate what happened from the story your mind is telling.',
    category: 'reality-check',
    duration: '3 min',
    steps: [
      'What actually happened? Just the facts, like a camera would see.',
      'What is my interpretation or story about it?',
      'What emotions is this story creating?',
      'Is there another way to interpret what happened?',
      'What would I tell a friend in this situation?',
      'What is the most balanced view I can hold right now?',
    ],
  },
  {
    id: 'c6',
    title: 'Mind Reading Check',
    description: 'Challenge the belief that you know what someone else is thinking.',
    category: 'reality-check',
    duration: '2 min',
    steps: [
      'What do I believe this person is thinking or feeling?',
      'What evidence do I actually have for this?',
      'Have I been wrong about reading minds before?',
      'What are 3 other possible explanations?',
      'Could they be dealing with something that has nothing to do with me?',
      'What would happen if I asked them directly?',
    ],
  },
  {
    id: 'c7',
    title: 'Opposite Action',
    description: 'Do the opposite of what your emotion urges you to do.',
    category: 'opposite-action',
    duration: '5 min',
    steps: [
      'Name the emotion you\'re feeling right now',
      'What is it urging you to do?',
      'Is acting on this urge effective for your goals?',
      'What is the OPPOSITE action?',
      'Do the opposite action ALL THE WAY',
      'For anger → be gentle. For shame → share. For fear → approach.',
    ],
  },
  {
    id: 'c8',
    title: 'Ride the Wave',
    description: 'Let the emotion pass through you without acting on it.',
    category: 'opposite-action',
    duration: '5 min',
    steps: [
      'Notice the emotion. Name it without judgment.',
      'Imagine it as a wave building in the ocean',
      'The wave rises... this is the hard part',
      'Stay still. Breathe. You don\'t have to do anything.',
      'The wave crests... and begins to fall',
      'Every wave passes. Every single one. Including this one.',
    ],
  },
];

export const VALIDATION_MESSAGES = [
  "What you're feeling is real and valid.",
  "This is incredibly hard, and you're still here.",
  "Your emotions make sense given what you've been through.",
  "You don't have to figure everything out right now.",
  "It's okay to not be okay.",
  "You are not too much. Your feelings are not too much.",
  "This moment will pass. You've survived every hard moment before this.",
  "You deserve the same compassion you'd give someone you love.",
  "Your pain doesn't define you. Neither does this moment.",
  "Reaching for support is strength, not weakness.",
];

export const BREATHING_PATTERNS = {
  calm: { inhale: 4, hold: 4, exhale: 6 },
  grounding: { inhale: 4, hold: 7, exhale: 8 },
  quick: { inhale: 3, hold: 0, exhale: 5 },
};
