export const REVENUECAT_IOS_API_KEY_ENV = 'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY';
export const REVENUECAT_ANDROID_API_KEY_ENV = 'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY';
export const REVENUECAT_TEST_API_KEY_ENV = 'EXPO_PUBLIC_REVENUECAT_TEST_API_KEY';

export const REVENUECAT_ENTITLEMENT_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID ?? 'BPD Companion Pro';

export const REVENUECAT_MONTHLY_PRODUCT_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_MONTHLY_PRODUCT_ID ?? 'bpd_monthly:monthly';

export const REVENUECAT_YEARLY_PRODUCT_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_YEARLY_PRODUCT_ID ?? 'bpd_yearly:annual';

export const REVENUECAT_OFFERING_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_OFFERING_ID ?? 'default';

export const REVENUECAT_ANDROID_MONTHLY_PRODUCT_ID = 'bpd_monthly';
export const REVENUECAT_ANDROID_MONTHLY_BASE_PLAN_ID = 'monthly';
export const REVENUECAT_ANDROID_MONTHLY_TRIAL_OFFER_ID = 'free-trial';

export const REVENUECAT_ANDROID_YEARLY_PRODUCT_ID = 'bpd_yearly';
export const REVENUECAT_ANDROID_YEARLY_BASE_PLAN_ID = 'annual';
export const REVENUECAT_ANDROID_YEARLY_TRIAL_OFFER_ID = 'free-trial';

export const REVENUECAT_TRIAL_DAYS = 3;
