export const REVENUECAT_IOS_API_KEY_ENV = 'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY';
export const REVENUECAT_ANDROID_API_KEY_ENV = 'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY';
export const REVENUECAT_TEST_API_KEY_ENV = 'EXPO_PUBLIC_REVENUECAT_TEST_API_KEY';

export const REVENUECAT_ENTITLEMENT_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID ?? 'BPD Companion Pro';

export const REVENUECAT_MONTHLY_PRODUCT_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_MONTHLY_PRODUCT_ID ?? 'bpd_companion_monthly';

export const REVENUECAT_YEARLY_PRODUCT_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_YEARLY_PRODUCT_ID ?? 'bpd_companion_yearly';

export const REVENUECAT_OFFERING_ID =
  process.env.EXPO_PUBLIC_REVENUECAT_OFFERING_ID ?? 'default';

export const REVENUECAT_TRIAL_DAYS = 7;
